### ISSUE TITLE
UI change on Play

### ISSUE THREAD

**Issue by akeshavan** [evictions/SwipesForScience#12]
- [x] instead of mouseover on field names, use small, gray text underneath
- [x] optimize space on screen (remove side margins so that PDF actually takes half) 
- [x] left side and right side independent scrolling

**Comment by otoomet** [comment]
adjustable boundary b/w pdf and annotation text for zooming one/the other part.  Maybe it should also allow for vertical placement?

**Comment by otoomet** [comment]
- currently on tall screen the UI only uses the upper part of the screen and wants you to scroll, even if there is plenty of space on screen underneath.  Note: the screen is just empty underneath the appi entry boxes:

![tall-screen](https://user-images.githubusercontent.com/13666380/55991598-75d43200-5c5f-11e9-9434-892337b57f8e.png)

**Comment by akeshavan** [comment]
{
  .widgetTemplate .row {
    height: 100VH;
  }
}
