### ISSUE TITLE
New keys + remove frontend parsing

### ISSUE THREAD

**Issue by akeshavan** [evictions/SwipesForScience#17]
These keys are sent to an endpoint to get a PDF & guessed address. Right now the endpoint requires multiple sources of information (case number, county, state, etc), but since each PDF has its own "key" attribute, we need to:

1. create endpoints that return a PDF & guessed address with a key
2. an endpoint that returns a list of keys on the server
3. update the AddressWidget to call the endpoint with the key (e.g. remove parsing)

**Comment by otoomet** [comment]
Implemented in this way:
* firebase has a list of "firekeys" (_sampleCounts_).  The firekeys are not directly parseeable (hash codes from the actual keys)
* added endpoints _/:firekey/address_, _/:firekey/files_, _/:firekey/pdffile64_.  API will figure out correct key (state-county-year-case) based on firekey.

I am closing this issue as I think we have implemented what is needed.
