### ISSUE TITLE
Wrong address between case file and OCR read

### ISSUE THREAD

**Issue by timathomas** [evictions/SwipesForScience#18]
The addresses are completely wrong between what's on the file and what's output on the fields. Attached is an example. Case number of interest is 09-2-13981. 
<img width="1088" alt="Screen Shot 2019-04-02 at 1 34 35 PM" src="https://user-images.githubusercontent.com/30070711/55435905-bc36dc00-554f-11e9-82d0-964820255a25.png">

**Comment by otoomet** [comment]
Most likely it is an issue with the address extraction algorithm, not the app.
