### ISSUE TITLE
& (ampersand) in file name

### ISSUE THREAD

**Issue by otoomet** [evictions/SwipesForScience#21]
Currently if file name contains `&`, the app sends a wrong request, cropped at the ampersand sign.  For instance, the firekey `05a72f458ad9a6a6adb551ca7f605d40` (Washington King 2006 06-2-24953-4) contains file `SummonsandComplaint-SUMMONS&COMPLAINT.pdf`.  In the API logs I can see request for `SummonsandComplaint-SUMMONS`.  My reading is the `&` is not converted to http-safe (e.g. %26) and hence considered as end of the file name.

**Comment by akeshavan** [comment]
encodeURI() -- converts &s to its code
