### ISSUE TITLE
A way to enter/view additional information

### ISSUE THREAD

**Issue by otoomet** [evictions/SwipesForScience#23]
The current webpage is fairly good for the basic info but there should be an option like _additional fields_ for things like court, building, county and such.

There should also be an option to see additional information, in particular

- [x]  file name where the address is coming from
- [x] list of all files.
- [x] case number
- [x] the estimated goodness measure

These are not needed for laymen but I occasionally feel the need to understand better what's going on there.

**Comment by akeshavan** [comment]
<b-collapse> in bootstrap-vue to hide extra stuff, but show it when the user clicks a button

**Comment by otoomet** [comment]
For instance, in case of pdf and extracted address mismatch, I'd like to know which file was the address extracted from.  This is returned when you query address, and show it somehow.  A usage case: 

The app shows unit number, but the default page shows correct address but no unit/unit number.  Is this extraction error, or is unit number there, just in another document?  The same address may be in a slightly different form in different documents. It is hard to walk through all of them looking for the one with unit number.

**Comment by ibhandari10** [comment]
Added filename and confidence. Casenumber is missing and needs to be sent from the Backend.

**Comment by otoomet** [comment]
Thanks @ibhandari10 and @AniruddhNathani !  Closing it now (and opening another one)
